# Generated by Django 4.1.5 on 2023-01-28 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataform', '0001_initial'),
        ('activation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('tipo_registro', models.CharField(choices=[('1', 'Não Autorizado'), ('2', 'Pedido'), ('3', 'Troca'), ('4', 'Devolução'), ('5', 'Garantia'), ('6', 'Consignado')], default='2', max_length=1)),
                ('status', models.CharField(choices=[('1', 'Não Iniciado'), ('2', 'Em Aberto'), ('3', 'Finalizado')], default='2', max_length=1)),
                ('nf', models.PositiveIntegerField(blank=True, null=True, verbose_name='nota fiscal')),
                ('movimento', models.CharField(blank=True, choices=[('E', 'entrada'), ('S', 'saida')], max_length=1)),
                ('tipo_movimento', models.CharField(blank=True, choices=[('V', 'VENDA'), ('S', 'SERVIÇO'), ('C', 'COMPRA'), ('P', 'PRODUÇÃO'), ('I', 'INVENTÁRIO')], max_length=1)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
                ('funcionario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.partner')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EstoqueItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('saldo', models.PositiveIntegerField()),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='stock.estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.item')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='StockInventary',
            fields=[
            ],
            options={
                'verbose_name': 'registro de inventário',
                'verbose_name_plural': 'registros de inventário',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
        migrations.CreateModel(
            name='StockProduction',
            fields=[
            ],
            options={
                'verbose_name': 'registro de produção',
                'verbose_name_plural': 'registros de produção',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
        migrations.CreateModel(
            name='StockSale',
            fields=[
            ],
            options={
                'verbose_name': 'registro de venda',
                'verbose_name_plural': 'registros de vendas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
        migrations.CreateModel(
            name='StockService',
            fields=[
            ],
            options={
                'verbose_name': 'registro de serviço',
                'verbose_name_plural': 'registros de serviços',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
        migrations.CreateModel(
            name='StockShopping',
            fields=[
            ],
            options={
                'verbose_name': 'registro de compra',
                'verbose_name_plural': 'registros de compras',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
    ]
