# Generated by Django 4.1.5 on 2023-01-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_estoqueitens_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueitens',
            name='funcionario',
        ),
    ]
