# Generated by Django 4.1.5 on 2023-01-31 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_estoqueitens_saldo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ('-created',), 'verbose_name': 'estoque', 'verbose_name_plural': 'estoques'},
        ),
        migrations.AlterModelOptions(
            name='estoqueitens',
            options={'ordering': ('pk',), 'verbose_name': 'estoque de item', 'verbose_name_plural': 'estoque de itens'},
        ),
    ]
