# Generated by Django 4.1.5 on 2023-01-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_estoque_options_alter_estoqueitens_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='custo_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='estoqueitens',
            name='custo_unitario',
            field=models.FloatField(null=True),
        ),
    ]
