# Generated by Django 4.1.5 on 2023-02-08 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0002_alter_company_options_alter_tokenuser_options'),
        ('stock', '0010_estoqueitens_custo_unitario_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activation.company', verbose_name='Empresa'),
        ),
    ]
