# Generated by Django 4.1.5 on 2023-01-28 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_company', models.CharField(choices=[('MEI', 'MicroEmpreendedor Individual'), ('ME', 'Microempresa'), ('EPP', 'Empresa de Pequeno Porte')], default='MEI', max_length=3)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('token_company', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=250)),
                ('start_data', models.DateField()),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('insc_est', models.CharField(blank=True, max_length=20)),
                ('insc_mun', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('number', models.IntegerField(blank=True)),
                ('complement', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zipcode', models.CharField(blank=True, max_length=15)),
                ('google_maps_link', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('whatsapp_number', models.CharField(blank=True, max_length=25)),
                ('whatsapp_link', models.CharField(blank=True, max_length=250)),
                ('site_link', models.CharField(blank=True, max_length=250)),
                ('instagram_link', models.CharField(blank=True, max_length=250)),
                ('linkedin_link', models.CharField(blank=True, max_length=250)),
                ('facebook_link', models.CharField(blank=True, max_length=250)),
                ('user_company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activation.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
