# Generated by Django 4.1.5 on 2023-01-28 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('markup', models.FloatField(null=True)),
                ('commission', models.FloatField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
            ],
            options={
                'ordering': ('brand',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('markup', models.FloatField(null=True)),
                ('commission', models.FloatField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='UnMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un_med', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
            ],
            options={
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='PartnerSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
            ],
            options={
                'ordering': ('subgroup',),
            },
        ),
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
            ],
            options={
                'ordering': ('group',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nickname', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('document', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone1', models.CharField(max_length=20, null=True)),
                ('phone2', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=10, null=True)),
                ('compl', models.CharField(max_length=20, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('zipcode', models.CharField(max_length=20, null=True)),
                ('cnpj', models.CharField(max_length=30, null=True)),
                ('insc_est', models.CharField(max_length=30, null=True)),
                ('insc_mun', models.CharField(max_length=30, null=True)),
                ('rg', models.CharField(max_length=30, null=True)),
                ('cpf', models.CharField(max_length=30, null=True)),
                ('tit_eleitor', models.CharField(max_length=30, null=True)),
                ('zona', models.CharField(max_length=10, null=True)),
                ('secao', models.CharField(max_length=10, null=True)),
                ('ctps', models.CharField(max_length=30, null=True)),
                ('pis', models.CharField(max_length=30, null=True)),
                ('cert_reservista', models.CharField(max_length=30, null=True)),
                ('cnh', models.CharField(max_length=30, null=True)),
                ('data_nasc', models.DateField(default=django.utils.timezone.now)),
                ('data_admissao', models.DateField(default=django.utils.timezone.now)),
                ('data_demissao', models.DateField(default=django.utils.timezone.now)),
                ('banco', models.CharField(max_length=30, null=True)),
                ('agencia', models.CharField(max_length=30, null=True)),
                ('tipo_conta', models.CharField(max_length=30, null=True)),
                ('conta', models.CharField(max_length=30, null=True)),
                ('pix', models.CharField(max_length=30, null=True)),
                ('type_partners', models.CharField(choices=[('1', 'Cliente'), ('2', 'Fornecedor'), ('3', 'Transportadora'), ('4', 'Vendedor'), ('5', 'Funcionário')], default='1', max_length=1)),
                ('type_person', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default='J', max_length=1)),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataform.partnergroup')),
                ('subgroup', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataform.partnersubgroup')),
            ],
            options={
                'ordering': ('nickname',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('reference', models.CharField(max_length=20, null=True)),
                ('price_in_cash', models.FloatField(null=True)),
                ('price_term', models.FloatField(null=True)),
                ('price_promotion', models.FloatField(null=True)),
                ('price_custom', models.FloatField(null=True)),
                ('stock_qtd', models.FloatField(null=True)),
                ('stock_control', models.BooleanField()),
                ('stock_min', models.FloatField(null=True)),
                ('stock_max', models.FloatField(null=True)),
                ('stock_seg', models.FloatField(null=True)),
                ('lot_min', models.FloatField(null=True)),
                ('lot_mult', models.FloatField(null=True)),
                ('lead_time', models.FloatField(null=True)),
                ('code_ean', models.CharField(max_length=20, null=True)),
                ('code_dun', models.CharField(max_length=20, null=True)),
                ('code_fab', models.CharField(max_length=20, null=True)),
                ('length', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('weight_gross', models.FloatField(null=True)),
                ('weight_net', models.FloatField(null=True)),
                ('pack_master', models.FloatField(null=True)),
                ('pack_sale', models.FloatField(null=True)),
                ('ncm', models.CharField(max_length=20, null=True)),
                ('cst', models.CharField(max_length=20, null=True)),
                ('color', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(max_length=20, null=True)),
                ('material', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('type_item', models.CharField(choices=[('1', 'Produto para Revenda'), ('2', 'Produção Própria'), ('3', 'Serviço Prestado'), ('4', 'Matéria-Prima'), ('5', 'Consumo e Utilização'), ('6', 'Ativo Patrimonial')], default='S', max_length=1)),
                ('brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataform.brand')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataform.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
                ('un_med', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataform.unmed')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
