# Generated by Django 4.1.5 on 2023-01-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('brand',), 'verbose_name': 'marca', 'verbose_name_plural': 'marcas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category',), 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('title',), 'verbose_name': 'item', 'verbose_name_plural': 'itens'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('nickname',), 'verbose_name': 'parceiro', 'verbose_name_plural': 'parceiros'},
        ),
        migrations.AlterModelOptions(
            name='partnergroup',
            options={'ordering': ('group',), 'verbose_name': 'grupo de parceiros', 'verbose_name_plural': 'grupos de parceiros'},
        ),
        migrations.AlterModelOptions(
            name='partnersubgroup',
            options={'ordering': ('subgroup',), 'verbose_name': 'subgrupo de parceiros', 'verbose_name_plural': 'subgrupos de parceiros'},
        ),
        migrations.AlterModelOptions(
            name='unmed',
            options={'ordering': ('description',), 'verbose_name': 'unidade', 'verbose_name_plural': 'unidades'},
        ),
    ]
